project_id = "kymoxuucjfgotjlhkfua"

[functions.import-competitors]
verify_jwt = false

[functions.enrollment-data]
verify_jwt = false

[functions.verify-athlete]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.public-enrollment]
verify_jwt = false

[functions.send-competition-report]
verify_jwt = false

[functions.import-competitors]
verify_jwt = false